# Generated by Django 3.1.5 on 2021-02-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_song_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
    ]
