# Generated by Django 3.1.5 on 2021-02-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_remove_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/'),
        ),
    ]
